CC = clang
CFLAGS = -Wall -std=c99

# FIXME: how do I make a different executable based on the output files
# for example I want sldriver, dldriver
driver: slist.o

.PHONE: clean

clean:
	-rm *.o sldriver
